meta:
  name: list
  description: The list model

fields:
  _id:
    desc: Unique id
    type: objectid
    read: owner
    write: app

  name:
    desc: Name
    read: owner
    write: owner

  user_id:
    desc: User ID
    type: objectid
    read: all
    write: owner
