meta:
  name: user
  description: The user model

fields:
  _id:
    desc: Unique id
    type: objectid
    read: any
    write: app

  email:
    desc: User email
    type: string
    read: owner
    write: owner
