meta:
  name: project
  description: The project model

fields:
  _id:
    desc: Unique id
    type: objectid
    read: any
    write: app

  authorized:
    desc: Authorized
    read: admin
    write: admin

  link:
    desc: Model link
    read: any
    write: any

  goal:
    desc: Project goal
    type: float
    read: any
    write: any

  duration:
    desc: Model duration in days
    type: integer
    default: 60
    read: any
    write: any

  expires_at:
    desc: Model expiry date
    type: time
    read: any
    write: any

  location_data:
    desc: Model location data
    type: hash
    default: {}
    read: any
    write: any

  lists:
    desc: Model list
    type: array
    default: []
    read: any
    write: any

  reminders_sent:
    desc: Reminders sent?
    type: boolean
    default: false
    read: any
    write: any

  updated_at:
    desc: Updated at
    type: date
    read: any
    write: any
